name: .NET Tests

on:
  push:
    branches:
      - main
      - reports
  pull_request:
    branches:
      - main

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_NOLOGO: "1"
  DEBUG: ${{ vars.DEBUG }}
  PLAYWRIGHT_TRACE_PATH: ${{vars.PLAYWRIGHT_TRACE_PATH}}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore

      - name: Build
        run: dotnet build

      - name: Playwright install
        run: pwsh TechnicalAssessmentTests/bin/Debug/net9.0/playwright.ps1 install

      - name: Run tests
        run: make test

      - name: Upload test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TechnicalAssessmentTests/TestResults/

      - name: Upload Traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: '${{PLAYWRIGHT_TRACE_PATH}}/trace-*.zip'

  reporting:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download test results artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: TechnicalAssessmentTests/TestResults

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install reportgenerator tool
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          dotnet tool restore

      - name: Generate HTML Report
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          make report

      - name: Upload HTML Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report/

      - name: Upload Playwright Traces
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: ${{PLAYWRIGHT_TRACE_PATH}}